INSERT INTO employees (first_name, last_name, department, position, salary) VALUES
-- Characters from Lord of the Rings
('Frodo', 'Baggins', 'Research and Development', 'Product Specialist', 55000),
('Samwise', 'Gamgee', 'Customer Service', 'Support Specialist', 48000),
('Gandalf', 'the Grey', 'Management', 'Chief Strategist', 120000),
('Aragorn', 'Elessar', 'Operations', 'Logistics Manager', 87000),
('Legolas', 'Greenleaf', 'Marketing', 'Brand Ambassador', 68000),
('Gimli', 'Son of Gloin', 'Engineering', 'Senior Engineer', 95000),
('Boromir', 'Son of Denethor', 'Sales', 'Sales Associate', 62000),
('Meriadoc', 'Brandybuck', 'Finance', 'Accountant', 60000),
('Peregrin', 'Took', 'Human Resources', 'Recruiter', 58000),
('Faramir', 'Steward', 'Operations', 'Project Coordinator', 73000),
('Eowyn', 'of Rohan', 'Marketing', 'Content Specialist', 65000),
('Eomer', 'of Rohan', 'Sales', 'Regional Manager', 78000),
('Galadriel', 'Lady of Light', 'Executive', 'Chief Visionary Officer', 140000),
('Elrond', 'Half-elven', 'Research and Development', 'Lead Scientist', 110000),
('Saruman', 'the White', 'Research and Development', 'Chief Researcher', 115000),
('Smeagol', 'Gollum', 'Customer Service', 'Support Specialist', 45000),
('Bilbo', 'Baggins', 'Marketing', 'Copywriter', 50000),
('Treebeard', 'Ent', 'Operations', 'Environmental Specialist', 82000),
('Theoden', 'King', 'Management', 'General Manager', 90000),
('Denethor', 'Steward', 'Finance', 'Financial Analyst', 72000),
('Isildur', 'King', 'Executive', 'Chief Heritage Officer', 130000),
('Arwen', 'Undomiel', 'Human Resources', 'HR Specialist', 60000),
('Haldir', 'of Lorien', 'Operations', 'Field Coordinator', 70000),
('Grima', 'Wormtongue', 'Administration', 'Clerk', 42000),
('Radagast', 'the Brown', 'Research and Development', 'Naturalist', 65000),
('Tom', 'Bombadil', 'Research and Development', 'Special Projects Lead', 92000),
('Bard', 'the Bowman', 'Operations', 'Logistics Specialist', 72000),
('Thranduil', 'of Mirkwood', 'Executive', 'CEO', 150000),
('Beorn', 'the Skin-changer', 'Engineering', 'Environmental Engineer', 86000),
('Dain', 'Ironfoot', 'Engineering', 'Construction Manager', 95000),
('Gloin', 'Son of Groin', 'Finance', 'Tax Specialist', 70000),
('Balin', 'Son of Fundin', 'Finance', 'Financial Planner', 67000),
('Bofur', 'the Dwarf', 'Customer Service', 'Service Advisor', 48000),
('Bombur', 'the Dwarf', 'Customer Service', 'Support Specialist', 47000),
('Fili', 'the Dwarf', 'Sales', 'Junior Sales Associate', 53000),
('Kili', 'the Dwarf', 'Sales', 'Junior Sales Associate', 53000),
('Gothmog', 'Lieutenant of Morgul', 'Operations', 'Security Manager', 75000),
('Lurtz', 'Uruk-hai', 'Operations', 'Field Operative', 65000),
('Azog', 'the Defiler', 'Engineering', 'Field Engineer', 82000),
('Bolg', 'Son of Azog', 'Operations', 'Safety Officer', 70000),
('Shelob', 'the Spider', 'Research and Development', 'Biology Specialist', 72000),
('Ancalagon', 'the Black', 'Engineering', 'Structural Engineer', 100000),
('Gorbag', 'Orc', 'Customer Service', 'Support Specialist', 43000),
('Shagrat', 'Orc', 'Customer Service', 'Service Advisor', 45000),
('Elendil', 'the Tall', 'Executive', 'Chief Legacy Officer', 130000),
('Celeborn', 'Lord of Lorien', 'Administration', 'Administrative Manager', 70000),
('Cirdan', 'the Shipwright', 'Operations', 'Port Manager', 82000),
('Glorfindel', 'Elf-lord', 'Marketing', 'Public Relations Specialist', 68000);

